- alias: 00_start
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:  
    - delay: 00:00:10
    - service: script.turn_on
      entity_id: script.telegramm_start
    - delay: 00:00:01
    - service: mqtt.publish
      data_template:
        topic: "notification/alarm"
        payload_template: '000'
        retain: true
    - delay: 00:00:01
    - service: mqtt.publish
      data_template:
        topic: "notification/error"
        payload_template: '000'
        retain: true
    - delay: 00:00:01
    - service: mqtt.publish
      data_template:
        topic: "notification/info"
        payload_template: '000'
        retain: true
    - delay: 00:00:01
    - service: mqtt.publish
      data_template:
        topic: "notification/messages"
        payload_template: '000'
        retain: true
        
- alias: 00_udpate_entity
  initial_state: true
  trigger:    
   - platform: time_pattern
     seconds: '/30'
  action:    
  - service: homeassistant.update_entity
    entity_id:
       - sensor.last_boot_custom

