- alias: telegramm_reserve_start
  initial_state: false
  trigger:
  - platform: state
    entity_id: sensor.reserve_system_send
  action:
    - service: script.turn_on
      entity_id: script.telegramm_reserve_start
      
- alias: telegramm_reserve_report
  initial_state: false
  trigger:
  - platform: state
    entity_id: sensor.reserve_system_report
  action:
    - service: script.turn_on
      entity_id: script.telegramm_reserve_report