- alias: telegramm_main_start
  initial_state: false
  trigger:
  - platform: state
    entity_id: sensor.main_system_send
  action:
    - service: script.turn_on
      entity_id: script.telegramm_main_start
      
- alias: telegramm_main_report
  initial_state: false
  trigger:
  - platform: state
    entity_id: sensor.main_system_report
  action:
    - service: script.turn_on
      entity_id: script.telegramm_main_report
      
- alias: telegramm_main_offline
  initial_state: false
  trigger:
  - platform: state
    entity_id: sensor.reserve_system_main_offline
  action:
    - service: script.turn_on
      entity_id: script.telegramm_main_offline
      
- alias: telegramm_main_online
  initial_state: false
  trigger:
  - platform: state
    entity_id: sensor.reserve_system_main_online
  action:
    - service: script.turn_on
      entity_id: script.telegramm_main_online