- alias: telegramm_error_code
  initial_state: false
  trigger:
  - platform: state
    entity_id: sensor.mqtt_error_code
  action:
    - service: script.turn_on
      data_template:
       entity_id: >-
          {%- if states.sensor.mqtt_error_code.state  == '000' -%}
          script.stub
          {%- elif states.sensor.mqtt_error_code.state  == '001' -%}
          script.photo_door
          {%- elif states.sensor.mqtt_error_code.state  == '002' -%}
          script.telegramm_002
          {%- elif states.sensor.mqtt_error_code.state  == '003' -%}
          script.telegramm_003
          {%- elif states.sensor.mqtt_error_code.state  == '004' -%}
          script.video_reolink2
          {%- else -%}
          script.telegramm_unknown_error
          {%- endif -%}
    - delay: 00:00:01
    - service: mqtt.publish
      data_template:
        topic: "states/error"
        payload_template: '000'
        retain: true