homeassistant:
  # Name of the location where Home Assistant is running
  name: MQTT base
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  time_zone: Europe/Kiev

  customize: !include_dir_merge_named includes/customize
  packages: !include_dir_merge_named includes/packages

  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password
  
  whitelist_external_dirs :
   - /config

# Стандартный набор для интерфейса
# default_config:

# Ручная конфигурация
# Отображение панели настроек в интерфейсе
config:
history:

# Включение официального интерфейса
frontend:
  themes: !include_dir_merge_named themes
# Включение карты
map:
# Включение поддержки приложения
mobile_app:
# Отслеживание солнца
sun:
#Сканирование доступных устройств в сети
ssdp:
# API для предоставления информации о системе и ее компонентах
system_health:
# Сенсор для отображения последней версии НА
updater:
# Потоковое изображение с камер
stream:

# Text to speech
tts:
  - platform: google_translate

lovelace:
  mode: yaml
  resources:
   - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
     type: module
   - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
     type: module
  
recorder: !include includes/recorder.yaml
group: !include includes/groups.yaml
camera: !include includes/camera.yaml
binary_sensor: !include_dir_merge_list includes/bin_sensor
automation: !include_dir_merge_list includes/automation
sensor: !include_dir_merge_list includes/sensors
script: !include_dir_merge_named includes/scripts
# mqtt_statestream: !include includes/mqtt_statestream.yaml

input_text:
  filed_1:
    name: adress
    initial: device adress
 
mqtt:
  broker: core-mosquitto
  discovery: true
  discovery_prefix: homeassistant  
  username: mqtt
  password: mqtt

telegram_bot:
  - platform: polling
    api_key: !secret api_key_77
    allowed_chat_ids:
      - !secret chat_id_alex
      - !secret chat_id_olha
      - !secret chat_id_group
      
notify:
  - name: telegram_alex
    platform: telegram
    chat_id: !secret chat_id_alex
    
  - name: telegram_olha
    platform: telegram
    chat_id: !secret chat_id_olha
    
  - name: telegram_group
    platform: telegram
    chat_id: !secret chat_id_group
