title: Home Assistant - MQTT сервер
views:

  - title: Главная
    id: main
    icon: mdi:home-assistant
    

    cards:

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
             **Состояние сервера**
    
        - type: entities
          show_header_toggle: false
          entities:
          - entity: sensor.last_boot_custom
            name: Сервер в онлайне -
            icon: mdi:av-timer
          - entity: sensor.online_custom
            name: Home Assistant в онлайне -
            icon: mdi:clock
          - type: divider
          - entity: sensor.current_ha
            name: Установлен Home Assistant -
            icon: mdi:alpha-v-circle
          - entity: sensor.version
            name: Последний Home Assistant -
            icon: mdi:alpha-v-circle-outline
            
        - type: history-graph
          entities:
           - entity: sensor.maria_db_size
             name: Maria DB

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
               **Система**   

        - type: horizontal-stack
          cards:

          - type: gauge
            name: Загрузка CPU
            unit: '%'
            entity: sensor.processor_use
            severity:
               green: 0
               yellow: 60
               red: 85 

          - type: gauge
            name: Загрузка ОЗУ
            unit: '%'
            entity: sensor.memory_use_percent
            severity:
               green: 0
               yellow: 60
               red: 85 
               
        - type: horizontal-stack
          cards:

           - type: gauge
             name: Диск заполнен
             unit: '%'
             entity: sensor.disk_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85    
                
           - type: gauge
             name: Свободное место
             unit: 'Гб'
             entity: sensor.disk_free
             severity:
                red: 2
                yellow: 6
                green: 8

        - type: history-graph
          entities:
           - entity: sensor.cpu_temp
             name: Температура CPU


      - type: vertical-stack
        cards:

        - type: markdown
          content: >
           **База, резервное копирование**

        - type: entities
          show_header_toggle: false
          entities:
            - entity: script.ha_backup
              name: Снапшот
              icon: mdi:backup-restore 
            - entity: counter.backup_stage
              name: Фаза бэкапа - 
            - entity: sensor.backup_phaze
              name: Действие - 
            - entity: timer.backup
              name: Фаза завершается через - 
            - entity: sensor.last_google_backup
              icon: mdi:map-clock-outline
            - entity: sensor.last_google_filecount
              icon: mdi:file-search
            - entity: sensor.last_google_alreadycount
              icon: mdi:file-export
            - entity: sensor.last_google_backedupcount
              icon: mdi:google-plus-box
            - entity: sensor.last_google_deletedcount
              icon: mdi:file-remove
            - entity: sensor.last_google_deletedfromgoogle
              icon: mdi:folder-google-drive
              
  - title: Мониторинг
    id: statе
    icon: mdi:keyboard

    cards:

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
             **Состояние основного сервера**
        - type: entities
          show_header_toggle: false
          entities:
          - entity: sensor.main_state
            name: Raspberry Pi 3 B+ в онлайне -
            icon: mdi:clock-outline  
          - entity: sensor.last_google_backup_main
            name: Последний удачный бэкап - 
            icon: mdi:map-clock-outline
          - entity: sensor.main_scenario_group
            name: Бытовые сценарии
            icon: mdi:format-list-numbered

        - type: entities
          show_header_toggle: false
          entities:
          - entity: sensor.main_system_unavailable_now_light
            name: Недоступно светильников - 
            icon: mdi:lightbulb-off
          - entity: sensor.main_system_unavailable_now_switch
            name: Недоступно реле - 
            icon: mdi:power-plug-off
          - entity: sensor.main_system_unavailable_now_sensor
            name: Недоступно сенсоров - 
            icon: mdi:credit-card-wireless
          - entity: sensor.main_system_unavailable_now_binary_sensor
            name: Недоступно бинарных сенсоров - 
            icon: mdi:ab-testing

      - type: vertical-stack
        cards:
            
        - type: markdown
          content: >
             **Состояние резервного сервера**

        - type: entities
          show_header_toggle: false
          entities:
          - entity: sensor.reserve_state
            name: Khadas VIM2 в онлайне -
            icon: mdi:clock-outline
          - entity: sensor.last_google_backup_reserve
            name: Последний удачный бэкап - 
            icon: mdi:map-clock-outline
          - entity: sensor.reserve_scenario_group
            name: Бытовые сценарии
            icon: mdi:format-list-numbered

        - type: entities
          show_header_toggle: false
          entities:
          - entity: sensor.reserve_system_unavailable_now_light
            name: Недоступно светильников - 
            icon: mdi:lightbulb-off
          - entity: sensor.reserve_system_unavailable_now_switch
            name: Недоступно реле - 
            icon: mdi:power-plug-off
          - entity: sensor.reserve_system_unavailable_now_sensor
            name: Недоступно сенсоров - 
            icon: mdi:credit-card-wireless
          - entity: sensor.reserve_system_unavailable_now_binary_sensor
            name: Недоступно бинарных сенсоров - 
            icon: mdi:ab-testing
            
      - type: vertical-stack
        cards:

        - type: markdown
          content: >
             **Состояние тестового сервера**
        - type: entities
          show_header_toggle: false
          entities:
          - entity: sensor.test_state
            name: Тестовый Orange Pi One Plus в онлайне -
            icon: mdi:clock-outline  
          - entity: sensor.last_google_backup_test
            name: Последний удачный бэкап - 
            icon: mdi:map-clock-outline

  - title: Панель управления
    icon: mdi:tools

    cards:

      - type: vertical-stack
        cards:
        
        - type: markdown
          content: >
             **Реле**
        - type: entities
          show_header_toggle: false
          entities:
          - entity: switch.sonoff_1000d036a0_1
            name: Реле Sonoff micro USB
            icon: mdi:usb-port
            
        - type: entities
          title: Добавление Zigbee устройств
          show_header_toggle: false
          entities:
             - entity: input_boolean.zigbee_permit_join
             - entity: timer.zigbee_permit_join
             - entity: sensor.bridge_state


            
  - title: Автоматизации
    id: auto
    icon: mdi:script

    cards:

      - type: vertical-stack
        cards:
    
        - type: markdown
          content: >
             **Автоматизации** 
             
        - type: entities
          show_header_toggle: false
          entities:   
             
          - entity: automation.alarm_code
            name: Обработка alarm кодов - 
            icon: mdi:telegram
          - entity: automation.error_code
            name: Обработка error кодов - 
            icon: mdi:telegram
          - entity: automation.info_code
            name: Обработка info кодов - 
            icon: mdi:telegram
          - entity: automation.message_code
            name: Обработка message кодов - 
            icon: mdi:telegram

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
             **Сенсоры**
        - type: entities
          show_header_toggle: false
          entities:
          - entity: binary_sensor.alarm_auto
          - entity: sensor.alarm_code
            icon: mdi:alert-circle          
          - entity: sensor.error_code
            icon: mdi:alert-circle 
          - entity: sensor.info_code
            icon: mdi:alert-circle
          - entity: sensor.messages_code
            icon: mdi:alert-circle
          - entity: binary_sensor.boiler
            name: Режим бойлера - 
            icon: mdi:water-boiler
          - entity: binary_sensor.humidification
            name: Режим увлажнения воздуха - 

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
             **Скрипты**
        - type: entities
          show_header_toggle: false
          entities:
          - entity: script.test
            tap_action: 
              action: toggle
            name: Тестовые коды
            icon: mdi:telegram  
          - entity: script.video_reolink2
          - entity: script.photo_door
            
            